### ISSUE TITLE
Constaints Issue

### ISSUE THREAD

**Issue by CLappin** [RISCV-on-Microsemi-FPGA/M2S090-Security-Eval-Kit#5]
Issue spotted with the IO and Timing constraints in the MiV project.  
To fix this, open the constraints manager and select the IO attributes, select the check box for place and route. Then, in the Timing tab, and select the check boxes for synthesis, place and route and timing verification.  
This will be fixed as soon as possible.

Thanks, 
Ciaran

**Comment by kevinscully100** [comment]
Merged pull request #6 from CLappin/master
